<a href="https://colab.research.google.com/github/Harsh015raut/Pytorch-Tutorials/blob/main/Pytorch_Tensors_and_Gradients_Tut_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Basics: Tensors & Gradients

#### *Part 1 of "Pytorch: Zero to GANs"*

*This post is the first in a series of tutorials on building deep learning models with PyTorch, an open source neural networks library developed and maintained by Facebook. Check out the full series:*

In [19]:
import torch

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In [20]:
# Let us make a number tensor
t1 = torch.tensor(5.)
t1

tensor(5.)

`5.` is a shorthand for `5.0`. It is used to indicate to Python (and PyTorch) that you want to create a floating point number. We can verify this by checking the `dtype` attribute of our tensor:

Since we used `.` in front of number,it is stored as float32 object.

In [21]:
 t1.dtype

torch.float32

if we simply say '5', it will be stored as int64.

In [22]:
t1 = torch.tensor(5)
t1.dtype

torch.int64

Now we will create complex tensors

In [23]:
## Vector - 1D
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

Note that here we have not given `.` to 2,3,4 still they will get coverted to floating point numbers as tensors have dtype of numbers same.

In [24]:
#MAtrix - 2D
t3 = torch.tensor([[5.,6],
                  [7,8],
                  [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [25]:
# 3-d Array
t4 = torch.tensor([
    [[1,2,3]],
    [[4,5,6]]
])
t4

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor.

In [26]:

t1 = torch.tensor(5.)
print(t1)
t1.shape

tensor(5.)


torch.Size([])

In [27]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [28]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [29]:
print(t4)
t4.shape

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])


torch.Size([2, 1, 3])

## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look an example:

In [30]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad =True)
b = torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created 3 tensors `x`, `w` and `b`, all numbers. `w` and `b` have an additional parameter `requires_grad` set to `True`. We'll see what it does in just a moment.

Let's create a new tensor `y` by combining these tensors:

In [31]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch special is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. To compute the derivatives, we can call the `.backward` method on our result `y`.

In [32]:
# Compute derivatives
y.backward()

The derivates of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors.

In [33]:
# Display Gradients
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


As expected, `dy/dw` has the same value as `x` i.e. `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None`, because `x` doesn't have `requires_grad` set to `True`.

The "grad" in `w.grad` stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing
* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

In [34]:
import numpy as np
x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using `torch.from_numpy`.

In [35]:
# COvnert the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

We can convert a PyTorch tensor to a Numpy array using the `.numpy` method of a tensor.

In [36]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)